Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/07/2022
var

x,y: inteiro

inicio

leia(x,y)
se x > y entao
   escreval("x é maior")
senao
     se y > x entao
          escreval("y é maior")
     senao
          escreval("valores iguais")
     fimse
fimse


Fimalgoritmo